# Site settings
title: Ming's
email: feitian124@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ming's blog. code, dream, life and more...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.yunnuy.com" # the base hostname & protocol for your site
twitter_username: feitian124
github_username:  feitian124

# Build settings
markdown: kramdown
