permalink: /:year-:month-:day/:title/
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
  ]

paginate: 10
paginate_path: ":num"
baseurl: ""

title: "Ming's"
email: "feitian124@gmail.com"
description: "work, life, dream and more..."
github_username:  "feitian124"
swiftype_searchId: "zC5xCjTK4RWNk26-2V9m"
disqus_shortname: "mingblog"

url: "http://blog.yunnuy.com"
imgrepo: "http://blog.yunnuy.com/static/img"
#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"

