version: '3'
services:
  zookeeper:
    image: zookeeper:3.6
    container_name: zookeeper
    ports:
      - 2181:2181
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
  # zoonavigator:
  #   image: elkozmon/zoonavigator
  #   container_name: zoonavigator
  #   ports:
  #    - 9000:9000
  #   environment:
  #     HTTP_PORT: 9000
  #   restart: unless-stopped
